name: Hello World Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello DevSecOps World!"

      - name: Simulate build
        run: |
          echo "Building project..."
          sleep 5
          echo "Build finished"
